# Generated by Django 2.2.13 on 2020-07-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('op_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='奥鹏编号')),
                ('kayouli_id', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='卡友立货号')),
                ('factory_name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='工厂名')),
                ('goods_name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='货号')),
            ],
            options={
                'verbose_name': '产品列表',
                'verbose_name_plural': '产品列表',
                'db_table': 'goodsList',
            },
        ),
        migrations.CreateModel(
            name='ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera_name', models.CharField(max_length=32, unique=True, verbose_name='管理员名称')),
                ('opera_age', models.CharField(default='23', max_length=32, verbose_name='管理员年龄')),
            ],
            options={
                'verbose_name': '管理员信息表',
                'verbose_name_plural': '管理员信息表',
                'db_table': 'ops',
            },
        ),
        migrations.CreateModel(
            name='goodsInfo',
            fields=[
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='op_xadmin.goods')),
                ('color', models.CharField(default=None, max_length=100, verbose_name='颜色')),
                ('size', models.CharField(default=None, max_length=100, verbose_name='尺码')),
                ('normal_size_price', models.PositiveIntegerField(verbose_name='普码价格')),
                ('big_size_price', models.PositiveIntegerField(verbose_name='大码价格')),
            ],
            options={
                'verbose_name': '产品详细信息',
                'verbose_name_plural': '产品详细信息',
                'db_table': 'goodsDetails',
            },
        ),
    ]
