# Generated by Django 2.2.13 on 2020-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_xadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='big_size_price',
            field=models.PositiveIntegerField(default=None, verbose_name='大码价格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='color',
            field=models.CharField(default=None, max_length=100, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='goods',
            name='normal_size_price',
            field=models.PositiveIntegerField(default=None, verbose_name='普码价格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.CharField(default=None, max_length=100, verbose_name='尺码'),
        ),
        migrations.DeleteModel(
            name='goodsInfo',
        ),
    ]
